# ============================= Filebeat inputs ============================
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /tmp/log_threat/*.json
# ============================ Elasticsearch Output ========================
output.elasticsearch:
  enabled: true
  hosts: ["https://elasticsearch01:9200"]
  username: "elastic"
  password: "elastic9999"

  #ssl.certificate: "/usr/share/elasticsearch/config/certs/ca/ca.crt"
  #ssl.key: "/usr/share/elasticsearch/config/certs/ca/ca.key"
 
  #ssl:
    #certificate_authorities: "/usr/share/elasticsearch/config/certs/ca/ca.crt"
    #certificate: "/usr/share/elasticsearch/config/certs/filebeat/filebeat.crt"
    #key: "/usr/share/elasticsearch/config/certs/filebeat/filebeat.key"

processors:
  - add_docker_metadata:
      host: "unix:///host_docker/docker.sock"
