filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/logs/*.log  # مسیر لاگ‌های مورد نظر شما

output.elasticsearch:
  hosts: ["https://es01:9200", "https://es02:9200"]
  username: "elastic"
  password: "DT_FhvNgScdvN+putewU"
  ssl.certificate_authorities: ["/usr/share/filebeat/certs/ca/ca.crt"]


# filebeat.inputs:
# - type: log
#   enabled: true
#   paths:
#     - /var/log/*.log  # مسیر لاگ‌های مورد نظر شما

# output.elasticsearch:
#   hosts: ["https://es01:9200", "https://es02:9200"]
#   username: "elastic"
#   password: "DT_FhvNgScdvN+putewU"
#   ssl.certificate_authorities: ["/usr/share/filebeat/config/certs/ca/ca.crt"]
#   indices:
#     - index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"
#       when.equals:
#         event.dataset: "your_dataset"
#   setup.ilm.enabled: false  # اختیاری - غیرفعال کردن ILM
